import{a as b,S as L,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const A="48961514-d720aad073d42be14fd4daf93",C="https://pixabay.com/api/";async function h(t,s=1){try{const r=await b.get(C,{params:{key:A,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:15}});return{images:r.data.hits,totalHits:r.data.totalHits}}catch(r){return console.error("Error fetching images:",r),{images:[],totalHits:0}}}const g=document.querySelector(".gallery"),w=new L(".gallery a",{captionsData:"alt",captionDelay:250});function F(t,s){s===1&&(g.innerHTML="");const r=t.map(o=>`
        <li class="img-card">
            <a href="${o.largeImageURL}">
                <img 
                    src="${o.webformatURL}" 
                    alt="${o.tags}" 
                    data-source="${o.largeImageURL}" 
                />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${o.likes}</p>
                <p><strong>Views:</strong> ${o.views}</p>
                <p><strong>Comments:</strong> ${o.comments}</p>
                <p><strong>Downloads:</strong> ${o.downloads}</p>
            </div>
        </li>
    `).join("");g.insertAdjacentHTML("beforeend",r),w.refresh()}const u=document.querySelector("form"),p=document.querySelector(".loader-first"),m=document.querySelector(".loader-bottom"),i=document.querySelector(".btn-loadmore"),y=document.querySelector(".gallery");let a=1,f="",d="";u.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.querySelector("input").value.trim();if(!r){l.error({message:"Please fill in the field!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}d=r,r!==f&&(a=1,f=r,y.innerHTML=""),p.style.display="block",i.style.display="none";try{const{images:o,totalHits:e}=await h(d,a);if(!o.length){l.warning({message:"No images found. Try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),y.innerHTML="";return}F(o,a),a*15>=e?(i.style.display="none",l.error({message:"You've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})):i.style.display="block",a++}catch{l.error({message:"Error fetching images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{p.style.display="none"}u.reset()});i.addEventListener("click",async()=>{i.style.display="none",m.style.display="block";try{const{images:t,totalHits:s}=await h(d,a);t.length&&(F(t,a),a++,a*15>=s&&(i.style.display="none",l.error({message:"You've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})),v())}catch{l.error({message:"Error loading more images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{m.style.display="none",i.style.display="block"}});function v(){const t=document.querySelector(".img-card");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
