import{a as b,S as F,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const g of a.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&o(g)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const L="48961514-d720aad073d42be14fd4daf93",w="https://pixabay.com/api/";async function f(t,s=1){try{const r=await b.get(w,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:15}});return{images:r.data.hits,totalHits:r.data.totalHits}}catch(r){return console.error("Error fetching images:",r),{images:[],totalHits:0}}}const p=document.querySelector(".gallery"),A=new F(".gallery a",{captionsData:"alt",captionDelay:250});function h(t,s){s===1&&(p.innerHTML="");const r=t.map(o=>`
        <li class="img-card">
            <a href="${o.largeImageURL}">
                <img 
                    src="${o.webformatURL}" 
                    alt="${o.tags}" 
                    data-source="${o.largeImageURL}" 
                />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${o.likes}</p>
                <p><strong>Views:</strong> ${o.views}</p>
                <p><strong>Comments:</strong> ${o.comments}</p>
                <p><strong>Downloads:</strong> ${o.downloads}</p>
            </div>
        </li>
    `).join("");p.insertAdjacentHTML("beforeend",r),A.refresh()}const m=document.querySelector("form"),c=document.querySelector(".loader"),d=document.querySelector(".loader-bottom"),i=document.querySelector(".btn-loadmore");let n=1,y="",u="";m.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.querySelector("input").value.trim();if(r===""){l.error({message:"Please fill in the field!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}u=r,r!==y&&(n=1,y=r),c&&(c.style.display="block",console.log("Loading message shown")),i.style.display="none";try{const{images:o,totalHits:e}=await f(u,n);if(!o||o.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}h(o,n),n*40>=e?(i.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})):i.style.display="block",n++}catch{l.error({message:"Error",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{c&&(c.style.display="none")}m.reset()});i.addEventListener("click",async()=>{d&&(i.style.display="none",d.style.display="block",console.log("Loading bottom message shown"));try{const{images:t,totalHits:s}=await f(u,n);t&&t.length>0&&(h(t,n),n++,n*40>=s&&(i.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})),C())}catch{l.error({message:"Error loading more images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{d&&(d.style.display="none",i.style.display="block")}});function C(){const t=document.querySelector(".img-card");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
