import{a as b,S as F,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const L="48961514-d720aad073d42be14fd4daf93",w="https://pixabay.com/api/";async function f(o,r=1){try{const t=await b.get(w,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15}});return{images:t.data.hits,totalHits:t.data.totalHits}}catch(t){return console.error("Error fetching images:",t),{images:[],totalHits:0}}}const p=document.querySelector(".gallery");function h(o,r){r===1&&(p.innerHTML="");const t=o.map(e=>`
        <li class="img-card">
            <a href="${e.largeImageURL}">
                <img 
                    src="${e.webformatURL}" 
                    alt="${e.tags}" 
                    data-source="${e.largeImageURL}" 
                />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",t),new F(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const m=document.querySelector("form"),c=document.querySelector(".loader"),g=document.querySelector(".loader-bottom"),i=document.querySelector(".btn-loadmore");let a=1,y="",u="";m.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.querySelector("input").value.trim();if(t===""){l.error({message:"Please fill in the field!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}u=t,t!==y&&(a=1,y=t),c&&(c.style.display="block",console.log("Loading message shown")),i.style.display="none";try{const{images:n,totalHits:e}=await f(u,a);if(!n||n.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}h(n,a),a*40>=e?(i.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})):i.style.display="block",a++}catch{l.error({message:"Error",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{c&&(c.style.display="none")}m.reset()});i.addEventListener("click",async()=>{g&&(i.style.display="none",g.style.display="block",console.log("Loading bottom message shown"));try{const{images:o,totalHits:r}=await f(u,a);o&&o.length>0&&(h(o,a),a++,a*40>=r&&(i.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})),A())}catch{l.error({message:"Error loading more images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{g&&(g.style.display="none",i.style.display="block")}});function A(){const o=document.querySelector(".img-card");if(o){const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
